// Code generated by protoc-gen-go. DO NOT EDIT.
// source: plugins.proto

package plugins

import (
	context "context"
	fmt "fmt"
	proto1 "github.com/anz-bank/sysl/src/proto"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GenerateCodeRequest struct {
	GeneratorName        string         `protobuf:"bytes,3,opt,name=generator_name,json=generatorName,proto3" json:"generator_name,omitempty"`
	Parameter            string         `protobuf:"bytes,1,opt,name=parameter,proto3" json:"parameter,omitempty"`
	Module               *proto1.Module `protobuf:"bytes,2,opt,name=module,proto3" json:"module,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GenerateCodeRequest) Reset()         { *m = GenerateCodeRequest{} }
func (m *GenerateCodeRequest) String() string { return proto.CompactTextString(m) }
func (*GenerateCodeRequest) ProtoMessage()    {}
func (*GenerateCodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a41a6b6d08976c8c, []int{0}
}

func (m *GenerateCodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateCodeRequest.Unmarshal(m, b)
}
func (m *GenerateCodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateCodeRequest.Marshal(b, m, deterministic)
}
func (m *GenerateCodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateCodeRequest.Merge(m, src)
}
func (m *GenerateCodeRequest) XXX_Size() int {
	return xxx_messageInfo_GenerateCodeRequest.Size(m)
}
func (m *GenerateCodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateCodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateCodeRequest proto.InternalMessageInfo

func (m *GenerateCodeRequest) GetGeneratorName() string {
	if m != nil {
		return m.GeneratorName
	}
	return ""
}

func (m *GenerateCodeRequest) GetParameter() string {
	if m != nil {
		return m.Parameter
	}
	return ""
}

func (m *GenerateCodeRequest) GetModule() *proto1.Module {
	if m != nil {
		return m.Module
	}
	return nil
}

type GenerateCodeResponse struct {
	// Error message if code generator failed. The Plugin should exit with zero
	// status code. Don't use this field to report problems with sysl itself
	// (e.g., failure to parse GenerateCodeRequest). Write an error message to
	// stderr and return a non-zero exit code instead.
	Error                string                             `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	OutputFile           []*GenerateCodeResponse_OutputFile `protobuf:"bytes,2,rep,name=output_file,json=outputFile,proto3" json:"output_file,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *GenerateCodeResponse) Reset()         { *m = GenerateCodeResponse{} }
func (m *GenerateCodeResponse) String() string { return proto.CompactTextString(m) }
func (*GenerateCodeResponse) ProtoMessage()    {}
func (*GenerateCodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a41a6b6d08976c8c, []int{1}
}

func (m *GenerateCodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateCodeResponse.Unmarshal(m, b)
}
func (m *GenerateCodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateCodeResponse.Marshal(b, m, deterministic)
}
func (m *GenerateCodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateCodeResponse.Merge(m, src)
}
func (m *GenerateCodeResponse) XXX_Size() int {
	return xxx_messageInfo_GenerateCodeResponse.Size(m)
}
func (m *GenerateCodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateCodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateCodeResponse proto.InternalMessageInfo

func (m *GenerateCodeResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *GenerateCodeResponse) GetOutputFile() []*GenerateCodeResponse_OutputFile {
	if m != nil {
		return m.OutputFile
	}
	return nil
}

type GenerateCodeResponse_OutputFile struct {
	// Relative to the output directory, without '..' path elements.
	Filename             string   `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Contents             string   `protobuf:"bytes,2,opt,name=contents,proto3" json:"contents,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateCodeResponse_OutputFile) Reset()         { *m = GenerateCodeResponse_OutputFile{} }
func (m *GenerateCodeResponse_OutputFile) String() string { return proto.CompactTextString(m) }
func (*GenerateCodeResponse_OutputFile) ProtoMessage()    {}
func (*GenerateCodeResponse_OutputFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_a41a6b6d08976c8c, []int{1, 0}
}

func (m *GenerateCodeResponse_OutputFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateCodeResponse_OutputFile.Unmarshal(m, b)
}
func (m *GenerateCodeResponse_OutputFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateCodeResponse_OutputFile.Marshal(b, m, deterministic)
}
func (m *GenerateCodeResponse_OutputFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateCodeResponse_OutputFile.Merge(m, src)
}
func (m *GenerateCodeResponse_OutputFile) XXX_Size() int {
	return xxx_messageInfo_GenerateCodeResponse_OutputFile.Size(m)
}
func (m *GenerateCodeResponse_OutputFile) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateCodeResponse_OutputFile.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateCodeResponse_OutputFile proto.InternalMessageInfo

func (m *GenerateCodeResponse_OutputFile) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *GenerateCodeResponse_OutputFile) GetContents() string {
	if m != nil {
		return m.Contents
	}
	return ""
}

func init() {
	proto.RegisterType((*GenerateCodeRequest)(nil), "plugins.GenerateCodeRequest")
	proto.RegisterType((*GenerateCodeResponse)(nil), "plugins.GenerateCodeResponse")
	proto.RegisterType((*GenerateCodeResponse_OutputFile)(nil), "plugins.GenerateCodeResponse.OutputFile")
}

func init() { proto.RegisterFile("plugins.proto", fileDescriptor_a41a6b6d08976c8c) }

var fileDescriptor_a41a6b6d08976c8c = []byte{
	// 308 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x51, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x25, 0x16, 0xab, 0x9d, 0x34, 0x1e, 0xd6, 0x1e, 0x42, 0xa8, 0x50, 0x8a, 0x4a, 0x2e, 0x4d,
	0x20, 0xfe, 0x03, 0x15, 0x8b, 0x88, 0x0a, 0x39, 0x8a, 0x50, 0x36, 0xe9, 0x18, 0x83, 0xc9, 0x6e,
	0xdc, 0x8f, 0x43, 0x3d, 0xf9, 0xc7, 0xfc, 0x6f, 0x92, 0xcd, 0x47, 0x15, 0xac, 0xb7, 0x7d, 0x6f,
	0x76, 0xde, 0xbc, 0x79, 0x03, 0x4e, 0x55, 0xe8, 0x2c, 0x67, 0x32, 0xa8, 0x04, 0x57, 0x9c, 0x1c,
	0xb4, 0xd0, 0x5b, 0x64, 0xb9, 0x7a, 0xd5, 0x49, 0x90, 0xf2, 0x32, 0xa4, 0xec, 0x63, 0x91, 0x50,
	0xf6, 0x16, 0xca, 0x8d, 0x2c, 0x42, 0x29, 0xd2, 0xd0, 0x7c, 0x36, 0xb0, 0xe9, 0x9b, 0x7f, 0x5a,
	0x70, 0xbc, 0x44, 0x86, 0x82, 0x2a, 0xbc, 0xe2, 0x6b, 0x8c, 0xf1, 0x5d, 0xa3, 0x54, 0xe4, 0x0c,
	0x8e, 0xb2, 0x86, 0xe6, 0x62, 0xc5, 0x68, 0x89, 0xee, 0x60, 0x66, 0xf9, 0xa3, 0xd8, 0xe9, 0xd9,
	0x07, 0x5a, 0x22, 0x99, 0xc2, 0xa8, 0xa2, 0x82, 0x96, 0xa8, 0x50, 0xb8, 0x96, 0xf9, 0xb1, 0x25,
	0xc8, 0x29, 0x0c, 0x4b, 0xbe, 0xd6, 0x05, 0xba, 0x7b, 0x33, 0xcb, 0xb7, 0xa3, 0x71, 0x60, 0x26,
	0xdf, 0x1b, 0x2e, 0x6e, 0x6b, 0xf3, 0x2f, 0x0b, 0x26, 0xbf, 0x2d, 0xc8, 0x8a, 0x33, 0x89, 0x64,
	0x02, 0xfb, 0x28, 0x04, 0xef, 0x84, 0x1b, 0x40, 0x6e, 0xc1, 0xe6, 0x5a, 0x55, 0x5a, 0xad, 0x5e,
	0x72, 0xa3, 0x3c, 0xf0, 0xed, 0xc8, 0x0f, 0xba, 0x38, 0xfe, 0x52, 0x0a, 0x1e, 0x4d, 0xc3, 0x4d,
	0x5e, 0x60, 0x0c, 0xbc, 0x7f, 0x7b, 0xd7, 0x00, 0xdb, 0x0a, 0xf1, 0xe0, 0xb0, 0x56, 0x34, 0xcb,
	0x36, 0x13, 0x7b, 0x5c, 0xd7, 0x52, 0xce, 0x14, 0x32, 0x25, 0xcd, 0x2e, 0xa3, 0xb8, 0xc7, 0xd1,
	0x33, 0x38, 0xf5, 0xb0, 0x65, 0x17, 0x0c, 0xb9, 0x83, 0xf1, 0x4f, 0x17, 0x64, 0xba, 0xc3, 0x9c,
	0x49, 0xda, 0x3b, 0xf9, 0xd7, 0xfa, 0xa5, 0xff, 0x74, 0xbe, 0xfb, 0xa2, 0x1b, 0x59, 0x44, 0x61,
	0xdb, 0x9e, 0x0c, 0xcd, 0x45, 0x2f, 0xbe, 0x03, 0x00, 0x00, 0xff, 0xff, 0x64, 0xa7, 0xd5, 0x27,
	0x1a, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CodeGeneratorClient is the client API for CodeGenerator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CodeGeneratorClient interface {
	GenerateCode(ctx context.Context, in *GenerateCodeRequest, opts ...grpc.CallOption) (*GenerateCodeResponse, error)
}

type codeGeneratorClient struct {
	cc *grpc.ClientConn
}

func NewCodeGeneratorClient(cc *grpc.ClientConn) CodeGeneratorClient {
	return &codeGeneratorClient{cc}
}

func (c *codeGeneratorClient) GenerateCode(ctx context.Context, in *GenerateCodeRequest, opts ...grpc.CallOption) (*GenerateCodeResponse, error) {
	out := new(GenerateCodeResponse)
	err := c.cc.Invoke(ctx, "/plugins.CodeGenerator/GenerateCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CodeGeneratorServer is the server API for CodeGenerator service.
type CodeGeneratorServer interface {
	GenerateCode(context.Context, *GenerateCodeRequest) (*GenerateCodeResponse, error)
}

func RegisterCodeGeneratorServer(s *grpc.Server, srv CodeGeneratorServer) {
	s.RegisterService(&_CodeGenerator_serviceDesc, srv)
}

func _CodeGenerator_GenerateCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CodeGeneratorServer).GenerateCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plugins.CodeGenerator/GenerateCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CodeGeneratorServer).GenerateCode(ctx, req.(*GenerateCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CodeGenerator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "plugins.CodeGenerator",
	HandlerType: (*CodeGeneratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateCode",
			Handler:    _CodeGenerator_GenerateCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugins.proto",
}
