package(default_visibility = ["//visibility:public"])

java_library(
    name = "sysl",
    srcs = [":sources"],
    deps = ["@joda_time_joda_time//jar"],
)

filegroup(
    name = "sources",
    srcs = glob(["**/*.java"]),
)
