ignore:
  - pkg/sysl_js/SyslLexer.js
  - pkg/sysl_js/SyslParser.js
  - pkg/sysl_js/SyslParserListener.js
  - pkg/ui/pkged.go
  - pkg/lspimpl/lspframework

coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 2%
    patch: off

comment:
  layout: "diff, flags, files"
