service:
  golangci-lint-version: 1.19.1
run:
  skip-files:
    - sysl2/sysl/grammar/sysl_lexer.go
    - sysl2/sysl/grammar/sysl_parser.go
    - sysl2/sysl/grammar/syslparser_base_listener.go
linters:
  enable-all: true
linters-settings:
  errcheck:
    check-blank: true
