service:
  golangci-lint-version: 1.23.3
run:
  timeout: 10m
  skip-files:
    - pkg/grammar/sysl_lexer.go
    - pkg/grammar/sysl_parser.go
    - pkg/grammar/syslparser_base_listener.go
    - pkg/ui/pkged.go
  skip-dirs:
    - pkg/lspimpl
linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - lll
    - misspell
    - nakedret
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - varcheck
    - whitespace
    - funlen
linters-settings:
  errcheck:
    check-blank: true
  funlen:
    lines: 146
    statements: 64

