service:
  golangci-lint-version: 1.19.1
run:
  skip-files:
    - sysl2/sysl/grammar/sysl_lexer.go
    - sysl2/sysl/grammar/sysl_parser.go
    - sysl2/sysl/grammar/syslparser_base_listener.go
linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - lll
    - misspell
    - nakedret
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - varcheck
    - whitespace
linters-settings:
  errcheck:
    check-blank: true

