run:
  timeout: 10m
  skip-files:
    - pkg/grammar/sysl_lexer.go
    - pkg/grammar/sysl_parser.go
    - pkg/grammar/syslparser_base_listener.go
    - pkg/ui/pkged.go
  skip-dirs:
    - pkg/lsp
linters:
  disable-all: true
  enable:
    - bodyclose
    # - deadcode  # deprecated
    # - depguard
    - dogsled
    - dupl
    - errcheck
    - gochecknoinits
    # - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    # - revive
    - gosec
    # - gosimple
    # - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - exportloopref
    - staticcheck
    # - structcheck  # deprecated
    - stylecheck
    - typecheck
    - unconvert
    - unused
    # - varcheck  # deprecated
    - whitespace
    - funlen
linters-settings:
  errcheck:
    check-blank: true
  funlen:
    lines: 146
    statements: 64
