project_name: sysl
env:
  - GO111MODULE=on
  - GOPROXY=https://proxy.golang.org
before:
  hooks:
    - go mod tidy

build:
  main: ./cmd/sysl
  ldflags:
    - -s -w -X main.Version=v{{.Version}}
    - -X main.GitCommit={{.ShortCommit}}
    - -X main.GitFullCommit={{.FullCommit}}
    - -X main.BuildDate={{.Date}}
    - -X main.BuildOS={{.Os}}/{{.Arch}}
    - -s -w -X "main.GoVersion={{.Env.GOVERSION}}"
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
    - arm64

archives:
- id: "sysl"
  builds: ['sysl']
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  replacements:
    darwin: darwin
    linux: linux
    windows: windows
    openbsd: openBSD
    netbsd: netBSD
    freebsd: freeBSD
    dragonfly: dragonFlyBSD
  name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}"
  files:
    - README.md
    - LICENSE

checksum:
  name_template: '{{.ProjectName}}_{{.Version}}_checksums.txt'
snapshot:
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - typo

brews:
  -
    name: Sysl
    homepage: "https://sysl.io/"
    description: "Sysl generates code and documentation from system specifications"

    # IDs of the archives to use.
    ids:
    - sysl

    # Github repository to push the tap to.
    tap:
      owner: anz-bank
      name: homebrew-sysl

    download_strategy: CurlDownloadStrategy

    # Git author used to commit to the repository.
    # Defaults are shown.
    commit_author:
      name: goreleaserbot
      email: goreleaser@carlosbecker.com

    # Folder inside the repository to put the formula.
    folder: Formula

    test: |
      system "#{bin}/sysl --version"
