language: python
python:
  - "2.7"
branches:
  only:
  - /.*/
env:
  - SYSL_PLANTUML=http://www.plantuml.com/plantuml
install:
  - pip install .
script:
  - python setup.py lint
  - python setup.py test
