language: python
python:
  - "2.7"
matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
      language: generic
env:
  - SYSL_PLANTUML=http://www.plantuml.com/plantuml
before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew list python >/dev/null 2>&1 || brew install python; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export PATH=/usr/local/opt/python/libexec/bin:$PATH; fi
install:
  - pip install . pytest flake8
script:
  - flake8
  - pytest
  - if [ "$TRAVIS_OS_NAME" != "osx" ]; then cd test/java && gradle test; fi
fast_finish: true
