environment:
  PYTHON: "C:\\Python27"

install:
  - "%PYTHON%\\python.exe setup.py install"

build: off

test_script:
  - "%PYTHON%\\python.exe setup.py test"
  - "%PYTHON%\\python.exe setup.py lint"
