environment:
  PYTHON: "C:\\Python27"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "pip install --upgrade setuptools"
  - "python setup.py install"

build: off

test_script:
  - "python setup.py test"
  - "python setup.py lint"
