py_binary(
    name = "import_swagger",
    srcs = ["import_swagger.py"],
    main = "import_swagger.py",
    deps = [
        "//src/util",
    ],
)

py_binary(
    name = "import_xsd",
    srcs = ["import_xsd.py"],
    main = "import_xsd.py",
    deps = [
        "//src/util",
    ],
)
