swagger: "2.0"
info:
  title: Simple
paths:
  /test:
    get:
      responses:
        200:
          description: 200 OK
          schema:
            $ref: '#/definitions/VeryAdvObj'

definitions:
  VeryAdvObj:
    type: object
    properties:
      name:
        type: int
      dummy:
        $ref: 'EXTERNAL_REF.yaml#/definitions/AdvObj'
      dummy2:
        $ref: 'morefolder/EXTERNAL_REF_2.yaml#/definitions/AnotherObj'
