py_library(
    name = "util",
    srcs = [
        "algo.py",
        "cache.py",
        "confluence.py",
        "datamodel.py",
        "debug.py",
        "diagutil.py",
        "file.py",
        "java.py",
        "jsonutil.py",
        "rex.py",
        "scopes.py",
        "simple_parser.py",
        "writer.py",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//src/proto:sysl",
    ],
)
