py_binary(
    name = "js_model",
    srcs = ["js_model.py"],
    visibility = ["//visibility:public"],
    deps = [
        "//src/proto:sysl",
        "//src/sysl:sysllib",
        "//src/util",
    ],
)
