// Code generated by protoc-gen-go. DO NOT EDIT.
// source: demo/codegen/AuthorisationAPI/AuthorisationAPI.proto

package AuthorisationAPI

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Operation int32

const (
	Operation_OPERATION_INVALID  Operation = 0
	Operation_OPERATION_READ     Operation = 1
	Operation_OPERATION_TRANSACT Operation = 2
	Operation_OPERATION_APPROVE  Operation = 3
)

var Operation_name = map[int32]string{
	0: "OPERATION_INVALID",
	1: "OPERATION_READ",
	2: "OPERATION_TRANSACT",
	3: "OPERATION_APPROVE",
}

var Operation_value = map[string]int32{
	"OPERATION_INVALID":  0,
	"OPERATION_READ":     1,
	"OPERATION_TRANSACT": 2,
	"OPERATION_APPROVE":  3,
}

func (x Operation) String() string {
	return proto.EnumName(Operation_name, int32(x))
}

func (Operation) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5fb08332341e520f, []int{0}
}

type AccountPermissions struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Permissions          []int64  `protobuf:"varint,2,rep,packed,name=permissions,proto3" json:"permissions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountPermissions) Reset()         { *m = AccountPermissions{} }
func (m *AccountPermissions) String() string { return proto.CompactTextString(m) }
func (*AccountPermissions) ProtoMessage()    {}
func (*AccountPermissions) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fb08332341e520f, []int{0}
}

func (m *AccountPermissions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountPermissions.Unmarshal(m, b)
}
func (m *AccountPermissions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountPermissions.Marshal(b, m, deterministic)
}
func (m *AccountPermissions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountPermissions.Merge(m, src)
}
func (m *AccountPermissions) XXX_Size() int {
	return xxx_messageInfo_AccountPermissions.Size(m)
}
func (m *AccountPermissions) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountPermissions.DiscardUnknown(m)
}

var xxx_messageInfo_AccountPermissions proto.InternalMessageInfo

func (m *AccountPermissions) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *AccountPermissions) GetPermissions() []int64 {
	if m != nil {
		return m.Permissions
	}
	return nil
}

type ListMeRequest struct {
	Operation            Operation `protobuf:"varint,2,opt,name=operation,proto3,enum=AuthorisationAPI.Operation" json:"operation,omitempty"`
	UserId               string    `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListMeRequest) Reset()         { *m = ListMeRequest{} }
func (m *ListMeRequest) String() string { return proto.CompactTextString(m) }
func (*ListMeRequest) ProtoMessage()    {}
func (*ListMeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fb08332341e520f, []int{1}
}

func (m *ListMeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMeRequest.Unmarshal(m, b)
}
func (m *ListMeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMeRequest.Marshal(b, m, deterministic)
}
func (m *ListMeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMeRequest.Merge(m, src)
}
func (m *ListMeRequest) XXX_Size() int {
	return xxx_messageInfo_ListMeRequest.Size(m)
}
func (m *ListMeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListMeRequest proto.InternalMessageInfo

func (m *ListMeRequest) GetOperation() Operation {
	if m != nil {
		return m.Operation
	}
	return Operation_OPERATION_INVALID
}

func (m *ListMeRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type ListMeResponse struct {
	Permissions          []*AccountPermissions `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ListMeResponse) Reset()         { *m = ListMeResponse{} }
func (m *ListMeResponse) String() string { return proto.CompactTextString(m) }
func (*ListMeResponse) ProtoMessage()    {}
func (*ListMeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fb08332341e520f, []int{2}
}

func (m *ListMeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMeResponse.Unmarshal(m, b)
}
func (m *ListMeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMeResponse.Marshal(b, m, deterministic)
}
func (m *ListMeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMeResponse.Merge(m, src)
}
func (m *ListMeResponse) XXX_Size() int {
	return xxx_messageInfo_ListMeResponse.Size(m)
}
func (m *ListMeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListMeResponse proto.InternalMessageInfo

func (m *ListMeResponse) GetPermissions() []*AccountPermissions {
	if m != nil {
		return m.Permissions
	}
	return nil
}

type MayIRequest struct {
	AccountId            string    `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Operation            Operation `protobuf:"varint,2,opt,name=operation,proto3,enum=AuthorisationAPI.Operation" json:"operation,omitempty"`
	UserId               string    `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MayIRequest) Reset()         { *m = MayIRequest{} }
func (m *MayIRequest) String() string { return proto.CompactTextString(m) }
func (*MayIRequest) ProtoMessage()    {}
func (*MayIRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fb08332341e520f, []int{3}
}

func (m *MayIRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MayIRequest.Unmarshal(m, b)
}
func (m *MayIRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MayIRequest.Marshal(b, m, deterministic)
}
func (m *MayIRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MayIRequest.Merge(m, src)
}
func (m *MayIRequest) XXX_Size() int {
	return xxx_messageInfo_MayIRequest.Size(m)
}
func (m *MayIRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MayIRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MayIRequest proto.InternalMessageInfo

func (m *MayIRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *MayIRequest) GetOperation() Operation {
	if m != nil {
		return m.Operation
	}
	return Operation_OPERATION_INVALID
}

func (m *MayIRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type MayIResponse struct {
	Reason               string   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	YouMay               bool     `protobuf:"varint,1,opt,name=you_may,json=youMay,proto3" json:"you_may,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MayIResponse) Reset()         { *m = MayIResponse{} }
func (m *MayIResponse) String() string { return proto.CompactTextString(m) }
func (*MayIResponse) ProtoMessage()    {}
func (*MayIResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fb08332341e520f, []int{4}
}

func (m *MayIResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MayIResponse.Unmarshal(m, b)
}
func (m *MayIResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MayIResponse.Marshal(b, m, deterministic)
}
func (m *MayIResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MayIResponse.Merge(m, src)
}
func (m *MayIResponse) XXX_Size() int {
	return xxx_messageInfo_MayIResponse.Size(m)
}
func (m *MayIResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MayIResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MayIResponse proto.InternalMessageInfo

func (m *MayIResponse) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *MayIResponse) GetYouMay() bool {
	if m != nil {
		return m.YouMay
	}
	return false
}

func init() {
	proto.RegisterEnum("AuthorisationAPI.Operation", Operation_name, Operation_value)
	proto.RegisterType((*AccountPermissions)(nil), "AuthorisationAPI.AccountPermissions")
	proto.RegisterType((*ListMeRequest)(nil), "AuthorisationAPI.ListMeRequest")
	proto.RegisterType((*ListMeResponse)(nil), "AuthorisationAPI.ListMeResponse")
	proto.RegisterType((*MayIRequest)(nil), "AuthorisationAPI.MayIRequest")
	proto.RegisterType((*MayIResponse)(nil), "AuthorisationAPI.MayIResponse")
}

func init() {
	proto.RegisterFile("demo/codegen/AuthorisationAPI/AuthorisationAPI.proto", fileDescriptor_5fb08332341e520f)
}

var fileDescriptor_5fb08332341e520f = []byte{
	// 388 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x53, 0xcf, 0x8f, 0x93, 0x40,
	0x14, 0x2e, 0xc5, 0xa0, 0xbc, 0x6a, 0x83, 0x2f, 0xb1, 0x36, 0x35, 0x55, 0x42, 0x3c, 0x10, 0x0f,
	0x6d, 0x52, 0xbd, 0x78, 0x32, 0xa3, 0xad, 0x86, 0xa4, 0x14, 0x32, 0xd6, 0xc6, 0x78, 0x69, 0x10,
	0x26, 0xca, 0x01, 0x86, 0x65, 0xe0, 0xc0, 0x6d, 0xff, 0x9e, 0xfd, 0x2b, 0x37, 0x6d, 0x61, 0x29,
	0x9d, 0xf4, 0xb8, 0xc7, 0xf9, 0xf8, 0xf2, 0xfd, 0x78, 0xef, 0x01, 0x9f, 0x22, 0x96, 0xf0, 0x79,
	0xc8, 0x23, 0xf6, 0x8f, 0xa5, 0x73, 0x52, 0x16, 0xff, 0x79, 0x1e, 0x8b, 0xa0, 0x88, 0x79, 0x4a,
	0x7c, 0x47, 0x02, 0x66, 0x59, 0xce, 0x0b, 0x8e, 0xc6, 0x25, 0x6e, 0xfd, 0x02, 0x24, 0x61, 0xc8,
	0xcb, 0xb4, 0xf0, 0x59, 0x9e, 0xc4, 0x42, 0xc4, 0x3c, 0x15, 0x38, 0x05, 0x08, 0x4e, 0xe8, 0x3e,
	0x8e, 0xc6, 0x8a, 0xa9, 0xd8, 0x3a, 0xd5, 0x6b, 0xc4, 0x89, 0xd0, 0x84, 0x41, 0xd6, 0xb2, 0xc7,
	0x7d, 0x53, 0xb5, 0x55, 0x7a, 0x0e, 0x59, 0x21, 0xbc, 0x58, 0xc7, 0xa2, 0x70, 0x19, 0x65, 0x37,
	0x25, 0x13, 0x05, 0x7e, 0x06, 0x9d, 0x67, 0x2c, 0x3f, 0xfa, 0x8e, 0xfb, 0xa6, 0x62, 0x0f, 0x17,
	0x6f, 0x66, 0x52, 0x4a, 0xaf, 0xa1, 0xd0, 0x96, 0x8d, 0xaf, 0xe1, 0x69, 0x29, 0x58, 0xde, 0x26,
	0xd1, 0x0e, 0x4f, 0x27, 0xb2, 0x7e, 0xc3, 0xb0, 0x31, 0x11, 0x19, 0x4f, 0x05, 0xc3, 0xef, 0xdd,
	0x60, 0x8a, 0xa9, 0xda, 0x83, 0xc5, 0x7b, 0xd9, 0x47, 0xae, 0xdc, 0x8d, 0x7f, 0xab, 0xc0, 0xc0,
	0x0d, 0x2a, 0xa7, 0x49, 0xdf, 0x9d, 0x87, 0x7a, 0x39, 0x8f, 0xc7, 0x28, 0xf7, 0x05, 0x9e, 0x9f,
	0x12, 0xd4, 0xd5, 0x46, 0xa0, 0xe5, 0x2c, 0x10, 0xb5, 0x81, 0x4e, 0xeb, 0xd7, 0x41, 0xa0, 0xe2,
	0xe5, 0x3e, 0x09, 0xaa, 0xa3, 0xc0, 0x33, 0xaa, 0x55, 0xbc, 0x74, 0x83, 0xea, 0x03, 0x03, 0xfd,
	0xc1, 0x11, 0x5f, 0xc1, 0x4b, 0xcf, 0x5f, 0x51, 0xb2, 0x75, 0xbc, 0xcd, 0xde, 0xd9, 0xec, 0xc8,
	0xda, 0x59, 0x1a, 0x3d, 0x44, 0x18, 0xb6, 0x30, 0x5d, 0x91, 0xa5, 0xa1, 0xe0, 0x08, 0xb0, 0xc5,
	0xb6, 0x94, 0x6c, 0x7e, 0x92, 0x6f, 0x5b, 0xa3, 0xdf, 0x95, 0x20, 0xbe, 0x4f, 0xbd, 0xdd, 0xca,
	0x50, 0x17, 0x77, 0x0a, 0x48, 0x57, 0x85, 0x2e, 0x68, 0x87, 0xcd, 0x24, 0x0c, 0xdf, 0xc9, 0x73,
	0xe8, 0x1c, 0xc6, 0xc4, 0xbc, 0x4e, 0x38, 0x35, 0xb7, 0x7a, 0xf8, 0x03, 0x9e, 0xb8, 0x41, 0x15,
	0xe3, 0x54, 0xe6, 0x9e, 0x6d, 0x69, 0xf2, 0xf6, 0xda, 0xe7, 0x46, 0xe8, 0x2b, 0xfe, 0x91, 0xb2,
	0xfe, 0xd5, 0x8e, 0xbf, 0xc6, 0xc7, 0xfb, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6d, 0xa4, 0x6b, 0x77,
	0x52, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthorisationAPIClient is the client API for AuthorisationAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthorisationAPIClient interface {
	Listme(ctx context.Context, in *ListMeRequest, opts ...grpc.CallOption) (*ListMeResponse, error)
	Mayi(ctx context.Context, in *MayIRequest, opts ...grpc.CallOption) (*MayIResponse, error)
}

type authorisationAPIClient struct {
	cc *grpc.ClientConn
}

func NewAuthorisationAPIClient(cc *grpc.ClientConn) AuthorisationAPIClient {
	return &authorisationAPIClient{cc}
}

func (c *authorisationAPIClient) Listme(ctx context.Context, in *ListMeRequest, opts ...grpc.CallOption) (*ListMeResponse, error) {
	out := new(ListMeResponse)
	err := c.cc.Invoke(ctx, "/AuthorisationAPI.AuthorisationAPI/Listme", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorisationAPIClient) Mayi(ctx context.Context, in *MayIRequest, opts ...grpc.CallOption) (*MayIResponse, error) {
	out := new(MayIResponse)
	err := c.cc.Invoke(ctx, "/AuthorisationAPI.AuthorisationAPI/Mayi", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthorisationAPIServer is the server API for AuthorisationAPI service.
type AuthorisationAPIServer interface {
	Listme(context.Context, *ListMeRequest) (*ListMeResponse, error)
	Mayi(context.Context, *MayIRequest) (*MayIResponse, error)
}

// UnimplementedAuthorisationAPIServer can be embedded to have forward compatible implementations.
type UnimplementedAuthorisationAPIServer struct {
}

func (*UnimplementedAuthorisationAPIServer) Listme(ctx context.Context, req *ListMeRequest) (*ListMeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Listme not implemented")
}
func (*UnimplementedAuthorisationAPIServer) Mayi(ctx context.Context, req *MayIRequest) (*MayIResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Mayi not implemented")
}

func RegisterAuthorisationAPIServer(s *grpc.Server, srv AuthorisationAPIServer) {
	s.RegisterService(&_AuthorisationAPI_serviceDesc, srv)
}

func _AuthorisationAPI_Listme_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorisationAPIServer).Listme(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AuthorisationAPI.AuthorisationAPI/Listme",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorisationAPIServer).Listme(ctx, req.(*ListMeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthorisationAPI_Mayi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MayIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorisationAPIServer).Mayi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AuthorisationAPI.AuthorisationAPI/Mayi",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorisationAPIServer).Mayi(ctx, req.(*MayIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthorisationAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "AuthorisationAPI.AuthorisationAPI",
	HandlerType: (*AuthorisationAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Listme",
			Handler:    _AuthorisationAPI_Listme_Handler,
		},
		{
			MethodName: "Mayi",
			Handler:    _AuthorisationAPI_Mayi_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "demo/codegen/AuthorisationAPI/AuthorisationAPI.proto",
}
