package codegen

import . "github.com/anz-bank/sysl/language/go/pkg/ast" //nolint:golint,stylecheck

// Prelude creates a comment group indicating a generated file that shouldn't be edited.
func Prelude() *CommentGroup {
	return Comments(
		Commentf("// Code generated by sysl DO NOT EDIT."),
	)
}
