/*TITLE : Petstore Schema*/
/* ---------------------------------------------
Autogenerated script from sysl
--------------------------------------------- */
ALTER TABLE Breed ALTER COLUMN breedName TYPE varchar (35);
ALTER TABLE Breed ALTER COLUMN numLegs TYPE varchar (1);
CREATE TABLE Company(
  abnNumber varchar (50),
  companyName varchar (30),
  companyCountry varchar (10),
  CONSTRAINT COMPANY_PK PRIMARY KEY(abnNumber)
);
CREATE TABLE Department(
  deptId integer,
  deptName varchar (40),
  deptLoc varchar (50),
  abn varchar (50),
  CONSTRAINT DEPARTMENT_PK PRIMARY KEY(deptId),
  CONSTRAINT DEPARTMENT_ABN_FK FOREIGN KEY(abn) REFERENCES Company (abnNumber)
);
ALTER TABLE Pet ADD COLUMN diet varchar (45);
ALTER TABLE Pet ALTER COLUMN numLegs TYPE varchar (1);
ALTER TABLE Pet ADD COLUMN petCounter bigserial;
ALTER TABLE Employee ADD COLUMN dept integer;
ALTER TABLE Employee ADD CONSTRAINT EMPLOYEE_DEPT_FK FOREIGN KEY(dept) REFERENCES Department (deptId);
ALTER TABLE Employee ALTER COLUMN name TYPE varchar (25);
