/*TITLE : Petstore Schema*/
/* ---------------------------------------------
Autogenerated script from sysl
--------------------------------------------- */
CREATE TABLE Employee(
  employeeId bigserial,
  name varchar (22),
  dob date,
  error integer,
  CONSTRAINT EMPLOYEE_PK PRIMARY KEY(employeeId)
);
CREATE TABLE Breed(
  breedId bigserial,
  breedName varchar (33),
  species varchar (50),
  numLegs integer,
  legRank integer,
  CONSTRAINT BREED_PK PRIMARY KEY(breedId)
);
CREATE TABLE Pet(
  petId bigserial,
  breedId integer,
  name varchar (50),
  dob date,
  numLegs integer,
  CONSTRAINT PET_PK PRIMARY KEY(petId),
  CONSTRAINT PET_BREEDID_FK FOREIGN KEY(breedId) REFERENCES Breed (breedId)
);
CREATE TABLE EmployeeTendsPet(
  employeeId integer,
  petId integer,
  CONSTRAINT EMPLOYEETENDSPET_PK PRIMARY KEY(employeeId,petId),
  CONSTRAINT EMPLOYEETENDSPET_EMPLOYEEID_FK FOREIGN KEY(employeeId) REFERENCES Employee (employeeId),
  CONSTRAINT EMPLOYEETENDSPET_PETID_FK FOREIGN KEY(petId) REFERENCES Pet (petId)
);
