py_binary(
    name = "reljam",
    srcs = ["reljam.py"],
    visibility = ["//visibility:public"],
    deps = [
        "//src/exporters/api:spring_rest",
        "//src/exporters/java",
        "//src/exporters/json_out:serializer",
        "//src/exporters/plantuml",
        "//src/exporters/swagger",
        "//src/exporters/xml",
        "//src/proto:sysl",
        "//src/sysl:sysllib",
        "//src/util",
    ],
)
