package datamodeldiagram

import (
	"testing"

	"github.com/alecthomas/assert"
	"github.com/anz-bank/sysl/pkg/mermaid"
	"github.com/anz-bank/sysl/pkg/parse"
	"github.com/anz-bank/sysl/pkg/syslutil"
	"github.com/anz-bank/sysl/pkg/syslwrapper"
	"github.com/spf13/afero"
)

func TestGenerateMermaidDataModelDiagram(t *testing.T) {
	m, err := parse.NewParser().Parse("demo/petshop/petshop.sysl",
		syslutil.NewChrootFs(afero.NewOsFs(), mermaid.ProjectDir))
	assert.NoError(t, err)
	mapper := syslwrapper.MakeAppMapper(m)
	mapper.IndexTypes()
	mapper.ConvertTypes()
	r, err := GenerateFullDataDiagram(m)
	assert.NotNil(t, m)
	assert.NotNil(t, r)
	assert.NoError(t, err)
}

func TestGenerateMermaidDataModelDiagramWithAppAndType(t *testing.T) {
	m, err := parse.NewParser().Parse("demo/petshop/petshop.sysl",
		syslutil.NewChrootFs(afero.NewOsFs(), mermaid.ProjectDir))
	assert.NoError(t, err)
	r, err := GenerateDataDiagramWithAppAndType(m, "PetShopModel", "Pet")
	assert.NotNil(t, m)
	assert.NotNil(t, r)
	assert.NoError(t, err)
}

func TestGenerateMermaidDataModelDiagramWithAppAndTypeNonExistentType(t *testing.T) {
	m, err := parse.NewParser().Parse("demo/petshop/petshop.sysl",
		syslutil.NewChrootFs(afero.NewOsFs(), mermaid.ProjectDir))
	assert.NoError(t, err)
	r, err := GenerateDataDiagramWithAppAndType(m, "PetShopModel", "ThisDoesNotExist")
	assert.NotNil(t, m)
	assert.NotNil(t, r)
	assert.NoError(t, err)
}

func TestGenerateMermaidDataModelDiagramWithAppAndTypeEmptyString(t *testing.T) {
	m, err := parse.NewParser().Parse("demo/petshop/petshop.sysl",
		syslutil.NewChrootFs(afero.NewOsFs(), mermaid.ProjectDir))
	assert.NoError(t, err)
	r, err := GenerateDataDiagramWithAppAndType(m, "PetShopModel", "")
	assert.NotNil(t, m)
	assert.NotNil(t, r)
	assert.NoError(t, err)
}

func TestGeneratePrimitive(t *testing.T) {
	r := GeneratePrimitive("String")
	expected := `%% AUTOGENERATED CODE -- DO NOT EDIT!

classDiagram
 class primitive{
  var String
 }`
	assert.Equal(t, expected, r)
}
