// Code generated by buildruntime.go; DO NOT EDIT.

package cfg

// Version   - Binary version
// GitCommit - Commit SHA of the source code
// BuildDate - Binary build date
// BuildOS   - Operating System used to build binary
//nolint:gochecknoglobals
const (
	Version   = `v0.5.1`
	GitCommit = `55f8989`
	BuildDate = `2020-01-17`
	BuildOS   = `darwin`
)
