package seqs

import (
	"bytes"
	"fmt"
	"io"
	"strings"
)

type SequenceDiagramWriter struct {
	ind            int
	atBeginOfLine  bool
	autogenWarning bool
	active         map[string]int
	properties     []string
	head           bytes.Buffer
	body           bytes.Buffer
}

func MakeSequenceDiagramWriter(autogenWarning bool, properties ...string) *SequenceDiagramWriter {
	p := make([]string, 0, len(properties))
	p = append(p, properties...)
	return &SequenceDiagramWriter{
		atBeginOfLine:  true,
		autogenWarning: autogenWarning,
		properties:     p,
		active:         map[string]int{},
	}
}

func (s *SequenceDiagramWriter) WriteTo(w io.Writer) (n int64, err error) {
	i, err := fmt.Fprint(w, s.String())

	return int64(i), err
}

func (s *SequenceDiagramWriter) Write(p []byte) (n int, err error) {
	newline := []byte("\n")
	newlines := bytes.Count(p, newline)
	if newlines == 0 {
		if s.atBeginOfLine {
			s.writeIndent()
		}
		n, err = s.body.Write(p)
		if err == nil {
			s.atBeginOfLine = false
		}
		return n, err
	}

	frags := bytes.SplitN(p, newline, newlines+1)

	for i, frag := range frags {
		if s.atBeginOfLine && len(frag) != 0 {
			s.writeIndent()
		}
		nn, err := s.body.Write(frag)
		if err != nil {
			return n, err
		}
		s.atBeginOfLine = false
		n += nn
		if i+1 < len(frags) {
			if err := s.WriteByte('\n'); err != nil {
				return n, err
			}
			n++
		}
	}
	s.atBeginOfLine = len(frags[len(frags)-1]) == 0
	return n, nil
}

func (s *SequenceDiagramWriter) WriteString(v string) (n int, err error) {
	return s.Write([]byte(v))
}

func (s *SequenceDiagramWriter) WriteByte(c byte) error {
	if s.atBeginOfLine {
		s.writeIndent()
	}

	err := s.body.WriteByte(c)
	if err == nil {
		s.atBeginOfLine = c == '\n'
	}

	return err
}

func (s *SequenceDiagramWriter) WriteHead(v string) {
	fmt.Fprintln(&s.head, v)
}

func (s *SequenceDiagramWriter) Indent() {
	s.ind++
}

func (s *SequenceDiagramWriter) Unindent() {
	if s.ind == 0 {
		panic("SequenceDiagramWriter unindent too far")
	}
	s.ind--
}

func (s *SequenceDiagramWriter) Activate(agent string) {
	s.active[agent]++

	fmt.Fprintf(s, "activate %s\n", agent)
}

func (s *SequenceDiagramWriter) Activated(agent string, suppressed bool) func() {
	if !suppressed {
		s.Activate(agent)
	}

	active := !suppressed

	return func() {
		if active {
			active = false
			s.Deactivate(agent)
		}
	}
}

func (s *SequenceDiagramWriter) Deactivate(agent string) {
	if v, ok := s.active[agent]; !ok || v == 0 {
		return
	}

	s.active[agent]--
	fmt.Fprintf(s, "deactivate %s\n", agent)

	if s.active[agent] == 0 {
		delete(s.active, agent)
	}
}

func (s *SequenceDiagramWriter) writeIndent() {
	if !s.atBeginOfLine {
		return
	}

	s.body.WriteString(strings.Repeat(" ", s.ind))
	s.atBeginOfLine = false
}

func (s *SequenceDiagramWriter) String() string {
	if s.body.Len() == 0 || s.head.Len() == 0 {
		return ""
	}

	var sb strings.Builder
	if s.autogenWarning {
		fmt.Fprintln(&sb, "''''''''''''''''''''''''''''''''''''''''''")
		fmt.Fprintln(&sb, "''                                      ''")
		fmt.Fprintln(&sb, "''  AUTOGENERATED CODE -- DO NOT EDIT!  ''")
		fmt.Fprintln(&sb, "''                                      ''")
		fmt.Fprintln(&sb, "''''''''''''''''''''''''''''''''''''''''''")
		fmt.Fprintln(&sb)
	}
	fmt.Fprintln(&sb, "@startuml")
	sb.WriteString(s.head.String())
	for _, p := range s.properties {
		fmt.Fprintln(&sb, p)
	}
	sb.WriteString(s.body.String())
	fmt.Fprintln(&sb, "@enduml")

	return sb.String()
}
