#!/usr/bin/env sh

# Will exit shell script if some error happen
set -o errexit 

arrai run ../../arrai/concat_go.arrai transformer.arrai \
| arrai eval '$"// Package avro ...\n// AUTOGENERATED. DO NOT EDIT.\npackage importer\n\n// nolint\nconst avroTransformerScript = `${//os.stdin}`"'\
> ./../full_avro_transformer_arrai.go
