swagger: "2.0"
info:
  title: Simple
paths:
  /test:
    get:
      responses:
        200:
          description: 200 OK
          schema:
            $ref: '#/definitions/AnotherObj'

definitions:
  AnotherObj:
    type: object
    properties:
      number:
        type: int

