py_test(
  name = "test_sysldata",
  srcs = ["test_sysldata.py"],
  size = "small",
  deps = ["//src/sysl:sysllib"],
  data = ["//test/data:test_data_group"],
)

py_test(
  name = "test_epa",
  srcs = ["test_epa.py"],
  size = "small",
  deps = ["//src/sysl:sysllib"],
  data = ["//test/data:test_data_group"],
)