openapi: "3.0.1"
info:
  title: Simple
paths:
  /pets:
    patch:
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/Cat'
                - $ref: '#/components/schemas/Dog'
      responses:
        '200':
          description: Updated
components:
  schemas:
    Dog:
      type: object
      properties:
        bark:
          type: boolean
        breed:
          type: string
          enum: [Dingo, Husky, Retriever, Shepherd]
    Cat:
      type: object
      properties:
        hunts:
          type: boolean
        age:
          type: integer
    Pet:
        type: object
        oneOf:
          - $ref: '#/components/schemas/Cat'
          - $ref: '#/components/schemas/Dog'
    # This is also currently unsupported
    # Feline:
    #   type: object
    #   oneOf:
    #     - $ref: '#/components/schemas/Cat'
    #     - type: object
    #       properties:
    #         hunts:
    #           type: boolean
    #         nocturnal:
    #           type: boolean
    #  Primitives in oneOf are currently unsupported
    # CatDog: 
    #     type: object
    #     oneOf:
    #       - type: string
    #         format: email
    #       - $ref: '#/components/schemas/Dog'

