openapi: "3.0"
info:
  title: Simple
paths:
  /test:
    get:
      responses:
        200:
          description: 200 OK
      parameters:
        - name: key
          schema:
            type: string
          required: false
          in: query
        - name: min_date
          schema:
            type: string
          required: true
          in: query
          format: date
