package mermaid

import (
	"strings"

	"github.com/anz-bank/sysl/pkg/parse"
	"github.com/anz-bank/sysl/pkg/syslutil"
)

const GeneratedHeader = "%% AUTOGENERATED CODE -- DO NOT EDIT!\n\n"
const ProjectDir = "../../../"

// CleanString replaces certain characters in the string suitable for mermaid
func CleanString(temp string) string {
	temp = parse.MustUnescape(temp)
	temp = strings.ReplaceAll(temp, " ", "")
	temp = strings.ReplaceAll(temp, "{", "_")
	temp = strings.ReplaceAll(temp, "}", "_")
	temp = strings.ReplaceAll(temp, "[", "_")
	temp = strings.ReplaceAll(temp, "]", "_")
	temp = strings.ReplaceAll(temp, "\"", "")
	temp = strings.ReplaceAll(temp, "~", "")
	temp = strings.ReplaceAll(temp, ":", "_")
	temp = strings.ReplaceAll(temp, "<", "")
	return temp
}

func CleanAppNames(appNames []string) []string {
	var cleanedAppNames []string
	for _, a := range appNames {
		cleanedAppNames = append(cleanedAppNames, syslutil.CleanAppName(a))
	}
	return cleanedAppNames
}
