java_test(
    name = "test",
    size = "small",
    srcs = [
        "TestPetShop.java",
    ],
    test_class = "TestPetShop",
    deps = [
        "//demo/petshop:api",
        "//demo/petshop:api_to_model",
        "//demo/petshop:facade",
        "//demo/petshop:model",
        "//demo/petshop:model_to_api",
        "//java/io/sysl",
        "@joda_time_joda_time//jar",
    ],
)
