project_name: sysl
env:
  - GO111MODULE=on
  - GOPROXY=https://proxy.golang.org
before:
  hooks:
    - go mod tidy

build:
  binary: sysl
  id: sysl
  main: ./cmd/sysl
  ldflags:
    - -s -w -X main.Version={{.Version}}
    - -X main.GitCommit={{.ShortCommit}}
    - -X main.BuildDate={{.Date}}
    - -X main.BuildOS={{.Os}}/{{.Arch}}
    - -s -w -X "main.GoVersion={{.Env.GOVERSION}}"
  goos:
    - darwin
    - linux
    - windows
    - freebsd
    - netbsd
    - openbsd
    - dragonfly
  goarch:
    - amd64
    - 386
    - arm
    - arm64
  goarm:
    - 7

dockers:
  - image_templates:
    - "docker.io/anzbank/sysl:latest"
    - "docker.io/anzbank/sysl:{{ .Version }}"

archives:
- id: "sysl"
  builds: ['sysl']
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  replacements:
    amd64: 64bit
    386: 32bit
    arm: ARM
    arm64: ARM64
    darwin: macOS
    linux: Linux
    windows: Windows
    openbsd: OpenBSD
    netbsd: NetBSD
    freebsd: FreeBSD
    dragonfly: DragonFlyBSD
  name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}"
  files:
    - README.md
    - LICENSE

checksum:
  name_template: '{{.ProjectName}}_{{.Version}}_checksums.txt'
snapshot:
changelog:
  skip: true
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - typo
