name: Check docs

on: [pull_request]

jobs:
  markdown-link-check:
    name: Check for broken links
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      working-directory: docs
      with:
        config-file: '.md-link-check-config.json'
        folder-path: 'docs,blog'
