name: Go-Windows

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build-and-test-windows:
    name: Build Windows and test
    runs-on: windows-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Get dependencies
        run: make deps
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Test
        run: .\scripts\test-with-coverage-windows.bat
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SYSL_PLANTUML: http://www.plantuml.com/plantuml

      - name: Set env
        run: $Env:GOVERSION=(go version); echo $Env:GOVERSION

      - name: Build sysl binary via goreleaser
        uses: goreleaser/goreleaser-action@master
        with:
          args: release --snapshot --skip-publish --rm-dist --debug -f .github/workflows/.goreleaser-go-windows.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # sysl_windows_amd64: according to https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#jobsjob_idruns-on
      # Windows Server 2019 supports 64-bit applications
      - name: Install sysl
        run: md %cd%\bin && copy .\dist\sysl_windows_amd64\sysl.exe %cd%\bin\sysl.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Test installed
        run: .\scripts\test-gosysl.bat
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOPATH: .
          SYSL_PLANTUML: http://www.plantuml.com/plantuml
