name: node-linux
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:

  build-and-test-sysl_js:
    name: Build and test sysl_js on linux
    runs-on: ubuntu-latest
    steps:

    - name: Set up Node
      uses: actions/setup-node@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Check out code
      uses: actions/checkout@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Install and test sysl_js
      run: |
        npm install --prefix unsorted/sysl_js
        npm test --prefix unsorted/sysl_js
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_AUTH_TOKEN: "SOME-RANDOM-KEY"
