name: Publish NPM Package for Sysl
on:
  push:
    branches:
      - master
    paths:
      - "ts/**"
      - .github/workflows/npm-publish.yaml

env:
  NPM_CONFIG_REGISTRY: ${{ vars.NPM_CONFIG_REGISTRY }}

jobs:
  check-version:
    runs-on: ${{ vars.RUNNER_UBUNTU && fromJSON(vars.RUNNER_UBUNTU) || 'ubuntu-latest' }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      # This one-liner will exit 1 if the current version in package.json exists in the registry.
      - name: Ensure new version
        run: |
          ! npm view @anz-bank/sysl versions --json | grep "$(node -e 'console.log(require("./package.json").version)')"
        working-directory: ts

      - name: Install Project
        if: ${{ github.repository_owner == 'anz-bank' }}
        run: yarn install --frozen-lockfile
        working-directory: ts

      - name: Publish Package
        if: ${{ github.repository_owner == 'anz-bank' }}
        run: npm publish
        working-directory: ts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
