name: Lint TypeScript
on:
  pull_request:
    branches:
      - master
    paths:
      - "ts/**"

env:
  NPM_CONFIG_REGISTRY: ${{ vars.NPM_CONFIG_REGISTRY }}

jobs:
  lint:
    runs-on: ${{ vars.RUNNER_UBUNTU && fromJSON(vars.RUNNER_UBUNTU) || 'ubuntu-latest' }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: |
          # install yarn if needed
          npm i -g yarn

          # switch registry in lock file
          if [ -n "${{ env.NPM_CONFIG_REGISTRY }}" ]; then
            sed -i'.bak' 's#https://registry.npmjs.org#${{ env.NPM_CONFIG_REGISTRY }}#' yarn.lock
            rm yarn.lock.bak
          fi

          yarn install --frozen-lockfile
        working-directory: ts

      - name: Check Code Formatting
        run: yarn prettier:check
        working-directory: ts

