name: Lint TypeScript
on:
  pull_request:
    branches:
      - master
    paths:
      - "ts/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "17.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install Dependencies
        run: yarn install --frozen-lockfile
        working-directory: ts

      - name: Check Code Formatting
        run: yarn prettier:check
        working-directory: ts

